name: ci
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

permissions:
  contents: read

jobs:
  plugin-ci:
    if: ${{ github.event_name != 'schedule' || github.repository_owner == 'mattermost' }}
    uses: mattermost/actions-workflows/.github/workflows/plugin-ci.yml@main
    secrets: inherit
